name: 'WebRTCApp_actions'
push: [main, dev]
pull_request:
  types:
    - opened
    - reopened
    - edited
    - synchronize
  branches: [main, dev]
  
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
      
        name: "Install dependencies"
        run: npm install

        name: "Build"
        run: npm run build

        name: "Prettier"
        run: npm run prettier